#!/bin/bash

# Install Ubuntu Restricted Extras 
function codecs {
if (whiptail --title "Multimedia Codecs" --yesno "Install Ubuntu Restricted Extras for multimedia playback?" 10 60) then
    # Install
    show_info 'Installing...'
    show_warning 'Requires root privileges'
    sudo apt-get install -y ubuntu-restricted-extras
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    main
else
    clear && main
fi
}