#!/bin/bash

# CONFIG
function config {
echo ''
show_question 'What would you like to do? '
echo ''
show_listitem '1. Set preferred application-specific settings?'
show_listitem '2. Show all startup applications?'
show_listitem '3. Disable system crash dialogs (apport)?'
show_listitem 'r. Return'
echo ''
show_question 'Enter your choice:' && read REPLY
case $REPLY in
# GSettings
1)
    # Font Sizes
    show_info'Setting font preferences...'
    gsettings set org.gnome.desktop.interface document-font-name 'Source Sans Pro 10' # This is a third-party font
    gsettings set org.gnome.desktop.interface font-name 'Source Sans Pro 10'
    gsettings set org.gnome.desktop.interface monospace-font-name 'Inconsolata 11' # This is also a third-party font
    gsettings set org.gnome.desktop.interface text-scaling-factor '1.0'
    gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Source Sans Pro Bold 9'
    gsettings set org.gnome.nautilus.desktop font 'Source Sans Pro 10'
    gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba'
    gsettings set org.gnome.settings-daemon.plugins.xsettings hinting 'slight'
    # Pantheon Settings
    show_info'Setting Pantheon app preferences...'
    org.pantheon.noise.settings update-folder-heirarchy false
    org.pantheon.terminal.settings font "Inconsolata 11"
    org.pantheon.desktop.wingpanel auto-adjust-alpha false
    org.pantheon.desktop.wingpanel background-alpha 0.6
    # GNOME Preferences
    show_info'Setting GNOME app preferences...'
    gsettings set org.gnome.nautilus.preferences sort-directories-first true
    gsettings set org.gnome.rhythmbox.rhythmdb monitor-library true
    gsettings set org.gnome.rhythmbox.sources browser-views 'artists-albums'
    # Done
    show_success "Done."
    config
    ;;
# Startup Applications
2)
    show_info 'Changing display of startup applications...'
    show_warning 'Requires root privileges:'
    sudo sed -i "s/NoDisplay=true/NoDisplay=false/g" /etc/xdg/autostart/*.desktop
    cd
    show_success 'Done.'
    config
    ;;
# Disable Apport
3)
    show_info 'Disabling apport crash dialogs...'
    show_warning 'Requires root privileges:'
    sudo sed -i "s/enabled=1/enabled=0/g" /etc/default/apport
    cd
    show_success 'Done.'
    config
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && config;;
esac
}