#!/bin/bash

# CONFIG
function config {
echo ''
show_info 'What would you like to do? '
echo ''
echo '1. Set preferred application-specific settings?'
echo '2. Show all startup applications?'
echo '3. Disable system crash dialogs (apport)?'
echo 'r. Return'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# GSettings
1)
    # Font Sizes
    echo 'Setting font preferences...'
    gsettings set org.gnome.desktop.interface text-scaling-factor '1.0'
    gsettings set org.gnome.desktop.interface document-font-name 'Source Sans Pro 10' # Default: Ubuntu 11
    gsettings set org.gnome.desktop.interface font-name 'Source Sans Pro 10' # Default: Ubuntu 11 
    gsettings set org.gnome.desktop.interface monospace-font-name 'Inconsolata Mono 11' # Default: Ubuntu Mono 11  
    gsettings set org.gnome.nautilus.desktop font 'Source Sans Pro 10' # Default: Ubuntu 11 
    gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Source Sans Pro Bold 9' # Default: Ubuntu Bold 11 
    gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba'
    gsettings set org.gnome.settings-daemon.plugins.xsettings hinting 'slight'
    # Unity Settings
    echo 'Setting Unity preferences...'
    gsettings set com.canonical.Unity.ApplicationsLens display-available-apps false
    gsettings set com.canonical.unity-greeter draw-user-backgrounds true 
    gsettings set com.canonical.indicator.power icon-policy 'charge'
    gsettings set com.canonical.Unity.Lenses remote-content-search 'none'
    # Nautilus Preferences
    echo 'Setting Nautilus preferences...'
    gsettings set org.gnome.nautilus.preferences sort-directories-first true
    # Rhythmbox Preferences
    echo 'Setting Rhythmbox preferences...'
    gsettings set org.gnome.rhythmbox.rhythmdb monitor-library true
    gsettings set org.gnome.rhythmbox.sources browser-views 'artists-albums'
    # Done
    echo "Done."
    config
    ;;
# Startup Applications
2)
    echo 'Changing display of startup applications...'
    show_info 'Requires root privileges:'
    sudo sed -i "s/NoDisplay=true/NoDisplay=false/g" /etc/xdg/autostart/*.desktop
    cd
    show_success 'Done.'
    config
    ;;
# Disable Apport
3)
    echo 'Disabling apport crash dialogs...'
    show_info 'Requires root privileges:'
    sudo sed -i "s/enabled=1/enabled=0/g" /etc/default/apport
    cd
    show_success 'Done.'
    config
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && config;;
esac
}