#!/bin/bash

# CUSTOMIZATION
function customize {
echo ''
show_question 'What would you like to do? '
echo ''
echo '1. Configure system?'
echo 'r. Return'
echo ''
show_question 'Enter your choice :' && read REPLY
case $REPLY in
    1) clear && config;; # System Configuration
    [Rr]*) clear && main;; # Return
    * ) clear && show_error '\aNot an option, try again.' && customize;; # Invalid choice
esac
}