#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

#INSTALL DESIGN TOOLS
DESTOOLS="$dir/data/design.list"

#INSTALL DESIGN TOOLS
function design {
echo ''
echo 'Installing design tools...'
echo ''
echo 'Current package list:'
echo ''
for package in $(cat $DESTOOLS)
do 
echo -e '\t'$package
done
echo ''
show_info 'Proceed? (Y)es, (N)o : ' && read REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* ) 
    show_info 'Requires root privileges:'
    # Feel free to change the contents of "design-tools.list" in the data folder to whatever suits your preference.
    sudo apt-get install -y $(cat $DESTOOLS)
    show_success 'Done.'
    main
    ;;
# Negative action
[Nn]* ) 
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.' && design
    ;;
esac
}