#!/bin/bash

#----- DECLARATIONS -----#

DEVTOOLS="data/development.list"

# INSTALL DEVELOPMENT TOOLS
function development {
echo ''
show_info 'What would you like to install? '
echo ''
echo '1. Development tools?'
echo '2. RVM dependencies?'
echo 'r. Return'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# Install Development Tools
1)
    echo 'Installing development tools...'
    echo ''
    echo 'Current package list:'
    echo ''
    for package in $(cat $DEVTOOLS)
    do 
    echo -e '\t'$package
    done
    echo ''
    read -p 'Proceed? (Y)es (N)o : ' REPLY
    echo ''
    case $REPLY in
    # Positive action
    [Yy]* ) 
        show_info 'Requires root privileges:'
        # Feel free to change the contents of "dev-tools.list" to whatever suits your preferences.
        sudo apt-get install -y $(cat $DEVTOOLS)
        show_success 'Done.'
        development
        ;;
    # Negative action
    [Nn]* )
        clear && development
        ;;
    # Error
    * )
        clear && echo 'Sorry try again.'
        development
        ;;
    esac
    ;;
# Install RVM dependencies
2)
    echo 'Installing RVM dependencies...'
    show_info 'Requires root privileges:'
    sudo apt-get install -y libreadline6-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libgdbm-dev libncurses5-dev bison libffi-dev
    show_success 'Done.'
    development
    ;;
# Return
[Rr]*) 
    clear && main;;
# Error
* )
    clear && echo 'Sorry try again.' && development
    ;;
esac
}