#!/bin/bash
#
# Update the list of packages in 'data/development.list' to suit your preferences


# Install preferred development apps
function development {
	show_header "Starting 'development' function..."
	# Check list
	DEVTOOLS="$(dirname "$0")/data/development.list"
	# Draw window
	if (eval `resize` && whiptail \
		--title "Preferred Development Applications" \
		--yesno "Current list of preferred development tools to install: \n\n$(cat $DEVTOOLS) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		echo 'Installing preferred development applications...'
		# Install loop
		for PACKAGE in $(cat $DEVTOOLS); do
			# Check if package is installed
			PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE | grep "install ok installed")
			# If app package is not installed
			if [ "" == "$PKGCHECK" ]; then
				# Install package
				show_info "'$PACKAGE' is not installed. Installing..."
				show_warning 'Requires root privileges'
				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
				# Done
				show_success 'Done.'
			else
				# Show already installed message
				show_success "Package '$PACKAGE' is installed."
			fi
		done
		# Finished
		echo "Installation complete"
		whiptail --title "Finished" --msgbox "Installation complete." 8 78
		main
	else
		main
	fi
}