#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

FAVS="$dir/data/favourites.list"

# INSTALL APPLICATIONS
function favourites {
# Install Favourite Applications
echo ''
show_info 'Installing favourite applications...'
echo ''
echo 'Current package list:'
echo ''
for package in $(cat $FAVS)
do
echo -e '\t'$package
done
echo ''
show_question 'Proceed? (Y)es, (N)o : ' && read REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* ) 
    show_warning 'Requires root privileges:'
    # Feel free to change the contents of 'favourites.list' in the data folder to whatever suits your preference.
    sudo apt-get install -y --no-install-recommends $(cat $FAVS)
    show_success 'Done.'
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.'
    favourites
    ;;
esac
}
