#!/bin/bash

dir="$(dirname "$0")"

FAVS="$dir/data/favourites.list"

# Install favourite applications using the list of packages 'data/favourites.list'
function favourites {
    if (eval `resize` && whiptail \
        --title "Favourite Applications" \
        --yesno "Current list of favourite applications to install: \n\n$(cat $FAVS) \n\nProceed with installation?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext ) then
        show_info 'Installing...'
        show_warning 'Requires root privileges'
        sudo apt-get install -y --no-install-recommends $(cat $FAVS)
        # Done
        show_success 'Done.'
        whiptail --title "Finished" --msgbox "Installation complete." 8 78
        main
    else
        clear && main
    fi
}