#!/bin/bash
#
# Update the list of packages in 'data/favs.list' to suit your preferences

# Install preferred applications 
function favs {
	display_title "Starting 'favs' function..."
	# Import list
	FAVS=$(dirname "$0")'/data/favs.list'
	# Draw Window
	if (eval `resize` && whiptail \
		--title "Preferred Applications" \
		--yesno "Current list of preferred applications to install: \n\n$(cat $FAVS) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		# Install loop
		display_info 'Installing preferred applications...'
		for PACKAGE in $(cat $FAVS); do
			# Check if package is installed
			PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE | grep "install ok installed")
			# If app package is not installed
			if [ "" == "$PKGCHECK" ]; then
				# Install package
				display_info "'$PACKAGE' is not installed. Installing..."
				display_warning 'Requires admin privileges'
				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
				# Done
				display_success "'$PACKAGE' installation is complete."
			else
				# Show already installed message
				echo "Package '$PACKAGE' is installed."
			fi
		done
		# Finish
		display_success "Installation complete."
		whiptail --title "Finished" --msgbox "Installation complete." 8 78
		main
	else
		main
	fi
}

