#!/bin/bash

dir="$(dirname "$0")"

FAVS="$dir/data/favs.list"

# Install preferred applications using the list of packages 'data/favs.list'
function favs {
	if (eval `resize` && whiptail \
		--title "Preferred Applications" \
		--yesno "Current list of preferred applications to install: \n\n$(cat $FAVS) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		# Install loop
		for PACKAGE in $(cat $FAVS); do
			# Check if package is installed
			PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE | grep "install ok installed")
			# If app package is not installed
			if [ "" == "$PKGCHECK" ]; then
				# Install package
				show_info "'$PACKAGE' is not installed. Installing..."
				show_warning 'Requires root privileges'
				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
				# Done
				show_success 'Done.'
			else
				# Show already installed message
				show_success "Package '$PACKAGE' is installed."
			fi
		done
		# Finish
		whiptail --title "Finished" --msgbox "Installation complete." 8 78
		main
	else
		main
	fi
}

