#!/bin/bash
#
# Update the list of packages in 'data/fonts.list' to suit your preferences

# Install preferred fonts
function install_fonts {
	display_title "Starting 'install_fonts' function..."
	# Check list
	FONTLIST=$(dirname "$0")'/data/fonts.list'
	# Draw window
	if (eval `resize` && whiptail \
		--title "Preferred Fonts" \
		--yesno "Current list of preferred fonts to install: \n\n$(for LINE in $(cat $FONTLIST); do echo '  '$LINE; done) \n\nProceed with installation?" \
		32 96 16 \
		--scrolltext) then
		# Install loop
		display_info 'Installing preferred fonts...'
		for PACKAGE in $(cat $FONTLIST); do
			# Check if package is installed
			PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE | grep "install ok installed")
			# If app package is not installed
			if [ "" == "$PKGCHECK" ]; then
				# Install package
				display_info "'$PACKAGE' is not installed. Installing..."
				# Admin privileges
				elevate_privilege "apt install -y --no-install-recommends $PACKAGE"
				# Done
				display_success "'$PACKAGE' installation is complete."
			else
				# Show already installed message
				echo "Package '$PACKAGE' is installed."
			fi
		done
		# Finish
		display_success "Installation complete."
		whiptail --title "Finished" --msgbox "Installation complete." 8 64
		fonts
	else
		fonts
	fi
}

# Install Microsoft Core Fonts
function msttcorefonts {
	display_title "Starting 'msttcorefonts' function..."
	# Variables
	PACKAGE=ttf-mscorefonts-installer
	NAME="Microsoft Core Fonts"
	# Check if already installed
	display_info 'Checking if already installed...'
	PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	if [ "" == "$PKGCHECK" ]; then
		display_info $NAME 'is not installed. Installing...'
		if (whiptail --title "Microsoft Core Fonts" --yesno "Install Microsoft Windows core fonts to extend font support?" 8 64) then
			# Install
			display_info 'Installing...'
			# Admin privileges
			elevate_privilege "apt install -y $PACKAGE"
			# Done
			display_success 'Done.'
			# Finished
			display_success "'$NAME' is installation complete."
			whiptail --title "Finished" --msgbox "Installation complete." 8 64
			fonts
		else
			fonts
		fi
	else
		# Already installed
		echo $NAME 'installed.'
		whiptail --title "Finished" --msgbox "$NAME are installed." 8 64
		fonts
	fi
}

# Install Fonts
function fonts {
	display_title "Starting 'fonts' function..."
	# check exit status
	exitstatus=$?
	if [ $exitstatus = 0 ]; then
		# Draw window
		$(eval `resize` && whiptail \
		--notags \
		--title "Install Fonts" \
		--menu "\nWhat would you like to do?" \
		--cancel-button "Go Back" \
		32 96 16 \
		install_fonts	'Install favourite fonts' \
		msttcorefonts	'Install Microsoft core fonts' \
		3>&1 1>&2 2>&3)
	else
		main
	fi
}