#!/bin/bash
#
# Update the list of packages in 'data/fonts.list' to suit your preferences

# Install preferred fonts
function install_fonts {
	echo_message title "Starting 'install_fonts' function..."
	# Check list
	FONTLIST=$(dirname "$0")'/data/fonts.list'
	# Draw window
	if (eval `resize` && whiptail \
		--title "Preferred Fonts" \
		--yesno "Current list of preferred fonts to install: \n\n$(for LINE in $(cat $FONTLIST); do echo '  '$LINE; done) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		# Install loop
		echo_message info 'Installing preferred fonts...'
		for PACKAGE in $(cat $FONTLIST); do
			# Check if package is installed
			check_packages $PACKAGE
			EXITSTATUS=$?
			# If package is not installed
			if [ $EXITSTATUS = 1 ]; then
				# Install package
				echo_message info "'$PACKAGE' is not installed. Installing..."
				# Admin privileges
				elevate_privilege "apt install -y --no-install-recommends $PACKAGE"
				# Done
				echo_message success "'$PACKAGE' installation is complete."
			else
				# Show already installed message
				echo "Package '$PACKAGE' is installed."
			fi
		done
		# Finish
		echo_message success "Installation complete."
		whiptail --title "Finished" --msgbox "Installation complete." 8 64
		fonts
	else
		fonts
	fi
}

# Install Microsoft Core Fonts
function msttcorefonts {
	echo_message title "Starting 'msttcorefonts' function..."
	# Variables
	PACKAGE=ttf-mscorefonts-installer
	NAME="Microsoft Core Fonts"
	# Check if already installed
	check_packages $PACKAGE
	EXITSTATUS=$?
	# If package is not installed
	if [ $EXITSTATUS = 1 ]; then
		echo_message info $NAME 'is not installed. Installing...'
		if (whiptail --title "Microsoft Core Fonts" --yesno "Install Microsoft Windows core fonts to extend font support?" 8 64) then
			# Install
			echo_message info 'Installing...'
			# Admin privileges
			elevate_privilege "apt install -y $PACKAGE"
			# Finished
			echo_message success "'$NAME' is installation complete."
			whiptail --title "Finished" --msgbox "Installation complete." 8 64
			fonts
		else
			fonts
		fi
	else
		# Already installed
		echo $NAME 'installed.'
		whiptail --title "Finished" --msgbox "$NAME are installed." 8 64
		fonts
	fi
}

# Install Fonts
function fonts {
	echo_message title "Starting 'fonts' function..."
	# check exit status
	EXITSTATUS=$?
	if [ $EXITSTATUS = 0 ]; then
		# Draw window
		$(eval `resize` && whiptail \
		--notags \
		--title "Install Fonts" \
		--menu "\nWhat would you like to do?" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		install_fonts	'Install favourite fonts' \
		msttcorefonts	'Install Microsoft core fonts' \
		3>&1 1>&2 2>&3)
	else
		main
	fi
}