#!/bin/bash

dir="$(dirname "$0")"

GNOMEDESKTOP="$dir/data/gnome-desktop.list"
GNOMEAPPS="$dir/data/gnome-apps.list"

# Cleanup System
function gnome {
	eval `resize` 
	GNOME=$(whiptail \
		--notags \
		--title "Install Latest GNOME" \
		--menu "\nWhat would you like to do?" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		gnome-upgrade   'Update to latest GNOME' \
		gnome-desktop   'Install basic GNOME desktop' \
		gnome-apps	  'Install GNOME core applications' \
		3>&1 1>&2 2>&3)
	 
	exitstatus=$?
	if [ $exitstatus = 0 ]; then
		$GNOME
	else
		main
	fi
}

# Add GNOME PPA
function gnome-upgrade {
	# Add repository
	show_info 'Adding GNOME3 PPA to software sources...'
	show_warning 'Requires root privileges'
	$SUDOCMD add-apt-repository -y ppa:gnome3-team/gnome3
	# Update repository information
	show_info 'Updating repository information...'
	$SUDOCMD apt update -y
	show_success 'Done.'
	# Upgrade GNOME
	show_info 'Updating repository information...'
	$SUDOCMD apt dist-upgrade -y
	show_success 'Done.'
	gnome
}

# Install GNOME Desktop
function gnome-desktop {
	if (eval `resize` && whiptail \
		--title "GNOME Desktop" \
		--yesno "Packages to install for a basic GNOME desktop: \n\n$(cat $GNOMEDESKTOP) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		# Install loop
		for PACKAGE in $(cat $GNOMEDESKTOP); do
			# Check if package is installed
			PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE | grep "install ok installed")
			# If app package is not installed
			if [ "" == "$PKGCHECK" ]; then
				# Install package
				show_info "'$PACKAGE' is not installed. Installing..."
				show_warning 'Requires root privileges'
				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
				# Done
				show_success 'Done.'
			else
				# Show already installed message
				show_success "Package '$PACKAGE' is installed."
			fi
		done
		# Finish
		whiptail --title "Finished" --msgbox "Installation complete." 8 78
		main
	else
		main
	fi
}

# Install GNOME Core Apps
function gnome-apps {
	if (eval `resize` && whiptail \
		--title "GNOME Core Apps"
		--yesno "Current list of GNOME core apps: \n\n$(cat $GNOMEAPPS) \n\nWould you like to install these apps?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext ) then
		# Install loop
		for PACKAGE in $(cat $GNOMEDESKTOP); do
			# Check if package is installed
			PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE | grep "install ok installed")
			# If app package is not installed
			if [ "" == "$PKGCHECK" ]; then
				# Install package
				show_info "'$PACKAGE' is not installed. Installing..."
				show_warning 'Requires root privileges'
				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
				# Done
				show_success 'Done.'
			else
				# Show already installed message
				show_success "Package '$PACKAGE' is installed."
			fi
		done
		# Finish
		whiptail --title "Finished" --msgbox "GNOME Apps are installed complete." 8 78
		main
	else
		gnome
	fi
}