#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

GEXTRAS="$dir/data/gnome-extras.list"

# INSTALL GNOME COMPONENTS
function gnome {
echo ''
show_listitem '\t1. Add GNOME3 PPA?'
show_listitem '\t2. Add GNOME3 Staging PPA?'
show_listitem '\t3. Install GNOME Shell?'
show_listitem '\t4. Install more GNOME components?'
show_listitem '\tr. Return.'
echo ''
read -p 'What would you like to do? (Enter your choice) : ' REPLY
case $REPLY in
# Add GNOME3 PPA
1)
    # Add repository
    show_info 'Adding GNOME3 PPA to software sources...'
    show_question 'Requires root privileges:'
    sudo add-apt-repository -y ppa:gnome3-team/gnome3
    # Update repository information
    show_info 'Updating repository information...'
    sudo apt-get update
    show_success 'Done.'
    # Upgrade system?
    read -p 'Perform system upgrade? (Y)es, (N)o : ' REPLY
    case $REPLY in
    # Positive action
    [Yy]* )
        show_question 'Requires root privileges:'
        sudo apt-get dist-upgrade -y
        show_success 'Done.'
        gnome
        ;;
    # Negative action
    [Nn]* )
        clear && gnome
        show_success 'Done.'
        ;;
    # Error
    * )
        clear && show_error '\aSorry, try again.'
        gnome
        ;;
    esac
    ;;
# Add GNOME3 Staging PPA
2)
    # Add repository
    echo 'Adding GNOME3 Staging PPA to software sources...'
    show_question 'Requires root privileges:'
    sudo add-apt-repository -y ppa:gnome3-team/gnome3-staging
    # Update repository information
    show_info 'Updating repository information...'
    sudo apt-get update
    show_success 'Done.'
    echo ''
    # Upgrade system?
    read -p 'Perform system upgrade? (Y)es, (N)o : ' REPLY
    case $REPLY in
    # Positive action
    [Yy]* )
        show_question 'Requires root privileges:'
        sudo apt-get dist-upgrade -y
        show_success 'Done.'
        gnome
        ;;
    # Negative action
    [Nn]* )
        clear && gnome
        show_success 'Done.'
        ;;
    # Error
    * )
        clear && show_error '\aSorry, try again.'
        gnome
        ;;
    esac
    ;;
# Install GNOME Shell
3)
    echo 'Installing GNOME Shell...'
    show_question 'Requires root privileges:'
    sudo apt-get install -y fonts-cantarell gdm gnome-shell gnome-shell-extensions gnome-session gnome-terminal nautilus
    show_success 'Done.'
    echo ''
    gnome
    ;;
# Install extra GNOME components
4)
    echo 'Installing extra GNOME components...'
    echo ''
    echo 'Current package list:'
    echo ''
    for package in $(cat $GEXTRAS)
    do 
    echo -e '\t'$package
    done
    echo ''
    show_question 'Proceed? (Y)es, (N)o : ' && read REPLY
    echo ''
    case $REPLY in
    # Positive action
    [Yy]* )
        show_question 'Requires root privileges:'
        # Feel free to change the contents of "gnome-extras.list" in the data folder to whatever suits your preference.
        sudo apt-get install -y $(cat $GEXTRAS)
        show_success 'Done.'
        gnome
        ;;
    # Negative action
    [Nn]* )
        clear && gnome
        ;;
    # Error
    * )
        clear && show_error '\aSorry, try again.'
        gnome
        ;;
    esac
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && gnome;;
esac
}