#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

UTILS="$dir/data/utilities.list"

# INSTALL SYSTEM TOOLS
function system {
packages=''
# Install Favourite System Utilities
echo 'Installing favourite system utilities...'
echo ''
echo 'Current package list:'
echo ''
for package in $(cat $UTILS)
do
	show_info 'Install '$package'? (Y)es, (N)o : ' && read REPLY1
	echo ''
	case $REPLY1 in
	[Yy]* )
		packages="$packages $package"
		;; 
	* )
		;;
	esac
done
clear && echo 'Packages selected: ' $packages
show_info 'Proceed? (Y)es, (N)o : ' && read REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* )
    show_info 'Requires root privileges:'
    # Feel free to change the contents of "utilities.list" in the data folder to whatever suits your preference.
    sudo apt-get install -y --no-install-recommends $packages
    show_success 'Done.'
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.'
    system
    ;;
esac
}
