#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

UTILS="$dir/data/utilities.list"

# INSTALL SYSTEM TOOLS
function system {
# Install Favourite System Utilities
echo 'Installing favourite system utilities...'
echo ''
echo 'Current package list:'
echo ''
for package in $(cat $UTILS)
do
echo -e '\t'$package
done
echo ''
show_info 'Proceed? (Y)es, (N)o : ' && read REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* )
    show_info 'Requires root privileges:'
    # Feel free to change the contents of "utilities.list" to whatever suits your preferences.
    sudo apt-get install -y --no-install-recommends $(cat $UTILS)
    show_success 'Done.'
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.'
    system
    ;;
esac
}