#!/bin/bash

# THIRD PARTY THEMES
function themes {
show_info 'What would you like to install? '
echo ''
echo '1. Moka Project'
echo 'r. Return'
echo ''
show_info 'Enter your choice :' && read REPLY
case $REPLY in
# Moka Icon Theme
1)
    # Add repository
    echo 'Adding Moka Icon Theme repository to sources...'
    show_info 'Requires root privileges:'
    sudo add-apt-repository -y ppa:moka/stable
    # Update repository information
    echo 'Updating repository information...'
    show_info 'Requires root privileges:'
    sudo apt-get update
    # Install package(s)
    echo 'Installing Moka icon themes...'
    show_info 'Requires root privileges:'
    sudo apt-get install -y moka-desktop
    show_success 'Done.'
    themes
    ;;
# Return
[Rr]*) 
    clear && customize;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && themes;;
esac
}