#!/bin/bash
#
# When adding (or removing) any functions remember to update the
# source list and function below to reflect any changes you make

dir=$(dirname "$0")

# Import apps functions; commented-out imports are omitted from the function below.

# source $dir/functions/apps/atom
source $dir/functions/apps/dropbox
source $dir/functions/apps/chrome
source $dir/functions/apps/flatpak
# source $dir/functions/apps/fontforge
source $dir/functions/apps/inkscape
# source $dir/functions/apps/mattermost
# source $dir/functions/apps/minecraft
# source $dir/functions/apps/oracle-java
source $dir/functions/apps/peek
source $dir/functions/apps/pia
source $dir/functions/apps/plex
source $dir/functions/apps/riot
source $dir/functions/apps/rvm
source $dir/functions/apps/slack
# source $dir/functions/apps/spotify
source $dir/functions/apps/steam
source $dir/functions/apps/sublime
# source $dir/functions/apps/synergy
# source $dir/functions/apps/vlc

# Install Third-Party Applications
function thirdparty {
	display_title "Starting 'thirdparty' function..."
	# check exit status
	EXITSTATUS=$?
	if [ $EXITSTATUS = 0 ]; then
		# Draw window
		$(eval `resize` && whiptail \
		--notags \
		--title "Third-Party Applications" \
		--menu "\nWhich third-party app would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'dropbox'		'Dropbox' \
		'flatpak'		'Flatpak' \
		'chrome'		'Google Chrome' \
		'inkscape'		'Inkscape' \
		'peek'			'Peek' \
		'pia'			'Private Internet Access' \
		'plex'			'Plex Media Server' \
		'riot'			'Riot Chat' \
		'rvm'			'Ruby Version Manager (RVM)' \
		'slack'			'Slack Desktop' \
		'steam'			'Steam' \
		'sublime'		'Sublime Text 3' \
		3>&1 1>&2 2>&3)
	else
		main
	fi
}