#!/bin/bash

# Perform system upgrade
function update {
if (whiptail --title "System Update" --yesno "Proceed with system update?" 10 60) then
    # Update repository information
    show_info 'Updating repository information...'
    show_warning 'Requires root privileges'
    sudo apt-get update
    # Dist-Upgrade
    show_info 'Performing system update...'
    sudo apt-get dist-upgrade -y
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "System update complete." 8 78
    main
else
    clear && main
fi
}