#!/bin/bash

# Perform system upgrade via apt
function update {
	echo_message title "Starting 'update' function..."
	# Draw window
	if (whiptail --title "System Update" --yesno "Proceed with system update?" 8 64) then
		# Update repository information
		echo_message info 'Updating repository information...'
		# Admin privileges
		elevate_privilege 'apt update -y'
		echo_message success 'Repository information updated.'
		# Upgrade
		echo_message info 'Performing system update...'
		# Admin privileges
		elevate_privilege 'apt dist-upgrade -y'
		# Check
		check_fail
		# Done
		echo_message success 'System update complete.'
		whiptail --title "Finished" --msgbox "System update complete." 8 64
	else
		main
	fi
}
