#!/bin/bash

# SYSTEM UPGRADE
function upgrade {
# Perform system upgrade
echo ''
show_info 'Proceed with system upgrade? (Y)es, (N)o : ' 
read REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* )
    # Update repository information
    echo 'Updating repository information...'
    show_info 'Requires root privileges:'
    sudo apt-get update
    # Dist-Upgrade
    echo 'Performing system upgrade...'
    sudo apt-get dist-upgrade -y
    show_success 'Done.'
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.'
    upgrade
    ;;
esac
}