#!/bin/bash
#
# Update the list of packages in 'data/utilities.list' to suit your preferences

# Install preferred utilities
function utilities {
	show_header "Starting 'utilities' function..."
	# Check list
	UTILS="$(dirname "$0")/data/utilities.list"
	# Draw window
	if (eval `resize` && whiptail --title \
		"Preferred System Utilities"  --yesno \
		"Current list of preferred system utilities: \n\n$(cat $UTILS) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext ) then
		# Install loop
		echo 'Installing preferred utilities...'
		for PACKAGE in $(cat $UTILS); do
			# Check if package is installed
			PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE | grep "install ok installed")
			# If app package is not installed
			if [ "" == "$PKGCHECK" ]; then
				# Install package
				show_info "'$PACKAGE' is not installed. Installing..."
				show_warning 'Requires root privileges'
				$SUDOCMD apt install -y --no-install-recommends $PACKAGE
				# Done
				show_success 'Done.'
			else
				# Show already installed message
				show_success "Package '$PACKAGE' is installed."
			fi
		done
		# Finish
		echo "Installation complete"
		whiptail --title "Finished" --msgbox "Installation complete." 8 78
		main
	else
		main
	fi
}