#!/bin/bash

dir="$(dirname "$0")"

UTILS="$dir/data/utilities.list"

# Install Preferred System Utilities
function utilities {
    if (eval `resize` && whiptail --title \
        "Preferred System Utilities"  --yesno \
        "Current list of preferred system utilities: \n\n$(cat $UTILS) \n\nProceed with installation?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext ) then
        show_info 'Installing...'
        show_warning 'Requires root privileges'
        # Feel free to change the contents of 'utilities.list' in the data folder to whatever suits your preference.
        sudo apt-get install -y --no-install-recommends $(cat $UTILS)
        # Done
        show_success 'Done.'
        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            whiptail --title "Finished" --msgbox "You've already installed these packages." 8 78
            main
        else
            whiptail --title "Finished" --msgbox "Installation complete." 8 78
            main
        fi
    else
        main
    fi
}