#!/bin/bash

# Atom
function atom {
	# Variables
	NAME="Atom"
	PACKAGE=atom
	VERSION=1.21.0
	# Install
	echo_message header 'Begin '$NAME' installation'
	# Check if package is installed
	check_packages $PACKAGE
	EXITSTATUS=$?
	# If package is not installed
	if [ $EXITSTATUS = 1 ]; then
		echo_message info $NAME 'is not installed.'
		echo 'Proceeding'
		echo_message info 'Downloading '$NAME'...'
		# Download Debian file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				whiptail --title "Error." --msgbox "No 32-bit version of this app available to download." 8 64
				;;
			x86_64)
				curl -O https://atom-installer.github.com/v${VERSION}/${PACKAGE}-amd64.deb
				;;
			*)
				whiptail --title "Error." --msgbox "No remote packages available to download." 8 64
				;;
		esac
		# Install package(s)
		echo_message info 'Installing '$NAME'...'
		# Admin privileges
		elevate_privilege "dpkg -i $PACKAGE*.deb"
		elevate_privilege "apt install -fy"
		# Cleanup and finish
		rm $PACKAGE*.deb
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		echo_message info $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}