#!/bin/bash

# Dropbox
function dropbox {
	# Variables
	NAME="Dropbox"
	PACKAGE=dropbox
	VERSION=2.10.0
	# Install
	display_header 'Begin '$NAME' installation'
	# Check if already installed
	display_info 'Checking if '$NAME' already installed...'
	PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	if [ "" == "$PKGCHECK" ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		display_info 'Downloading '$NAME'...'
		# Download Debian file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				curl -O https://linux.dropbox.com/packages/ubuntu/dropbox_${VERSION}_i386.deb
				;;
			x86_64)
				curl -O https://linux.dropbox.com/packages/ubuntu/dropbox_${VERSION}_amd64.deb
				;;
			*)
				whiptail --title "No remote packages available to download." --msgbox "Error." 8 64
				;;
		esac
		# Install package(s)
		display_info 'Installing '$NAME'...'
		# Admin privileges
		elevate_privilege "dpkg -i $PACKAGE*.deb"
		elevate_privilege "apt install -fy"
		# Cleanup and finish
		rm $PACKAGE*.deb
		# Done
		display_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		display_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}