#!/bin/bash

# Dropbox
function install_dropbox {
	# Variables
	NAME="Dropbox"
	PACKAGE="dropbox_2.10.0"
	REMOTE="https://linux.dropbox.com/packages/ubuntu"
	# Download and install remote package
	install_remote_package $NAME $PACKAGE $REMOTE install_thirdparty
}