#!/bin/bash

# Install FontForge from PPA
function install_fontforge {
	NAME="FontForge"
	PACKAGE="fontforge"
	# Do not include the "ppa:" bit, it will break other functions
	PPA="fontforge/fontforge"
	# Add PPA repository
	add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
	# check exit status
	if [ $? = 0 ]; then
		# Install package
		install_package "$NAME" "$PACKAGE" install_thirdparty
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		install_thirdparty
	else
		# Cancelled
		echo_message info "Installation of $NAME cancelled."
		# return
		install_thirdparty
	fi
}