#!/bin/bash

# FontForge
function fontforge {
	# Variables
	NAME="FontForge"
	PACKAGE=fontforge
	PPANAME=ppa:fontforge/fontforge
	# Install
	display_header 'Begin '$NAME' installation'
	# Check if already installed
	display_info 'Checking if '$NAME' already installed...'
	PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	if [ "" == "$PKGCHECK" ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		# Add repository
		display_info 'Adding '$NAME' repository to software sources...'
		elevate_privilege "add-apt-repository -y $PPANAME"
		# Update repository information
		display_info 'Updating repository information...'
		elevate_privilege "apt update -y"
		display_success 'Done.'
		# Install
		display_info 'Installing '$NAME'...'
		elevate_privilege "apt install -y $PACKAGE"
		# Done
		display_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		display_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}