#!/bin/bash

# PPA Function Template
#
# most of this template is complete, you'll just need to change the three variables and the function name
#
#	package_name = the name of the package you'll be installing from the PPA
#	ppa_url = the url of the PPA in the form ppa:user/ppa
#	app_name = a human readable name of the app you're installing
#
# next set the function_name and reference it in the 'thirdparty' function in the 'thirdparty' function file 
# and be sure to 'source' it in the list at the top of that file as well

function function_name {
	# Variables
	NAME="app_name"
	PACKAGE=package_name
	PPANAME=ppa_url
	# Install
	show_header 'Begin '$NAME' installation'
	# Check if already installed
	echo 'Checking if '$NAME' is already installed...'
	PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	if [ "" == "$PKGCHECK" ]; then
		echo $NAME 'is not installed. Proceeding'
		# Add repository
		show_info 'Adding '$NAME' repository to software sources...'
		show_warning 'Requires root privileges'
		sudo add-apt-repository -y $PPANAME
		# Update repository information
		show_info 'Updating repository information...'
		sudo apt update -y
		show_success 'Done.'
		# Install
		show_info 'Installing '$NAME'...'
		sudo apt install -y $PACKAGE
		# Done
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		thirdparty
	else
		# Already installed
		show_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		thirdparty
	fi
}