#!/bin/bash

# PPA Function Template
#
# most of this template is complete, you'll just need to change the three variables and the function name
#
#	package_name = the name of the package you'll be installing from the PPA
#	ppa_url = the url of the PPA in the form ppa:user/ppa
#	app_name = a human readable name of the app you're installing
#
# next set the function_name and reference it in the 'thirdparty' function in the 'thirdparty' function file 
# and be sure to 'source' it in the list at the top of that file as well

function function_name {
	# Variables
	NAME="app_name"
	PACKAGE=package_name
	PPANAME=ppa_url
	# Install
	display_header 'Begin '$NAME' installation'
	# Check if package is installed
	check_packages $PACKAGE
	exitstatus=$?
	# If package is not installed
	if [ $exitstatus = 1 ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		# Add repository
		display_info 'Adding '$NAME' repository to software sources...'
		elevate_privilege "add-apt-repository -y $PPANAME"
		# Update repository information
		display_info 'Updating repository information...'
		elevate_privilege "apt update -y"
		display_success 'Done.'
		# Install
		display_info 'Installing '$NAME'...'
		elevate_privilege "apt install -y $PACKAGE"
		# Done
		display_success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		display_info $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}