#!/bin/bash

# Java
function oracle-java {
	# Variables
	NAME="Oracle Java 9"
	PACKAGE=oracle-java9-installer
	PPANAME=ppa:webupd8team/java
	# Install
	display_header 'Begin '$NAME' installation'
	# Check if package is installed
	check_packages $PACKAGE
	exitstatus=$?
	# If package is not installed
	if [ $exitstatus = 1 ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		# Add repository
		display_info 'Adding '$NAME' repository to software sources...'
		elevate_privilege "add-apt-repository -y $PPANAME"
		# Update repository information
		display_info 'Updating repository information...'
		elevate_privilege "apt update -y"
		display_success "Installation of '$PACKAGE' complete."
		# Install
		display_info 'Installing '$NAME'...'
		elevate_privilege "apt install -y $PACKAGE"
		# Done
		display_success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		display_info $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}