#!/bin/bash

# Peek
function peek {
	# Variables
	NAME="Peek"
	PACKAGE=peek
	PPANAME=ppa:peek-developers/daily
	# Install
	display_header 'Begin '$NAME' installation'
	# Check if already installed
	display_info 'Checking if '$NAME' already installed...'
	PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	if [ "" == "$PKGCHECK" ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		# Add repository
		display_info 'Adding '$NAME' repository to software sources...'
		display_warning 'Requires admin privileges'
		$SUDOCMD add-apt-repository -y $PPANAME
		# Update repository information
		display_info 'Updating repository information...'
		$SUDOCMD apt update -y
		display_success 'Done.'
		# Install
		display_info 'Installing '$NAME'...'
		$SUDOCMD apt install -y $PACKAGE
		# Done
		display_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		thirdparty
	else
		# Already installed
		display_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		thirdparty
	fi
}