#!/bin/bash

# Plex
function plex {
	# Variables
	NAME="Plex"
	PACKAGE=plexmediaserver
	LIST=plexmediaserver.list
	KEY='https://downloads.plex.tv/plex-keys/PlexSign.key'
	REPO='deb https://downloads.plex.tv/repo/deb ./public main'
	# Install
	echo_message header 'Begin '$NAME' installation'
	# Check if package is installed
	check_packages $PACKAGE
	EXITSTATUS=$?
	# If package is not installed
	if [ $EXITSTATUS = 1 ]; then
		echo_message info $NAME 'is not installed.'
		echo 'Proceeding'
		# Check if repository already exists
		echo_message info 'Checking if '$NAME' repository is already added...'
		if [ ! -f /etc/apt/sources.list.d/${LIST} ]; then
			# Add the repository signing key to be able to verify downloaded packages
			echo_message info 'Adding '$NAME' signing key to keyring...'
			# Download Key
			curl -sL $KEY | elevate_privilege "apt-key add -"
			# Done
			echo_message success "Installation of '$PACKAGE' complete."
			# Add the repository
			echo_message info 'Adding '$NAME' repository to software sources...'
			# Write repository to apt sources list file
			echo $REPO | elevate_privilege "tee /etc/apt/sources.list.d/${LIST}"
			# Update repository information
			echo_message info 'Updating repository information...'
			elevate_privilege "apt update -y"
			echo_message success "Installation of '$PACKAGE' complete."
		else
			echo_message info $NAME 'repository already in software sources.'
		fi
		# Install
		echo_message info 'Installing '$NAME'...'
		elevate_privilege "apt install -y $PACKAGE"
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		echo_message info $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}