#!/bin/bash

# Riot
function riot {
	# Variables
	NAME="Riot"
	PACKAGE=riot-web
	LIST=riot-im.list
	KEY='https://riot.im/packages/debian/repo-key.asc'
	REPO="deb https://riot.im/packages/debian/ $(lsb_release -cs) main"
	# Install
	show_header 'Begin '$NAME' installation'
	# Check if already installed
	echo 'Checking if '$NAME' already installed...'
	PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	if [ "" == "$PKGCHECK" ]; then
		echo $NAME 'is not installed. Proceeding'
		# Check if repository already exists
		echo 'Checking if '$NAME' repository already existed...'
		if [ ! -f /etc/apt/sources.list.d/${LIST} ]; then
			# Add the repository signing key to be able to verify downloaded packages
			show_info 'Adding '$NAME' signing key to keyring...'
			show_warning 'Requires root privileges'
			# Download key
			$SUDOCMD curl -L $KEY | $SUDOCMD apt-key add -
			# Done
			show_success 'Done.'
			# Add the repository
			show_info 'Adding '$NAME' repository to software sources...'
			show_warning 'Requires root privileges'
			# Write repository to apt sources list file
			echo $REPO | $SUDOCMD tee /etc/apt/sources.list.d/${LIST}
			# Update repository information
			show_info 'Updating repository information...'
			$SUDOCMD apt update -y
			show_success 'Done.'
		else
			echo ''$NAME' repository already in software sources.'
		fi
		# Install
		show_info 'Installing '$NAME'...'
		$SUDOCMD apt install -y $PACKAGE
		# Done
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		thirdparty
	else
		# Already installed
		show_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		thirdparty
	fi
}