#!/bin/bash

# RVM
function rvm {
	# Variables
	NAME="Ruby Version Manager"
	KEYID='409B6B1796C275462A1703113804BB82D39DC0E3'
	KEYSERVER='hkp://keys.gnupg.net'
	# Check if already installed
	display_info 'Checking if '$NAME' already installed...'
	if [ ! -f $HOME/.rvm/installed.at ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		# Check if key already exists in keyring
		KEYCHECK=$(gpg --list-keys | grep -w ${KEYID})
		if [ "" == "$KEYCHECK" ]; then
			# Add the repository signing key to be able to verify downloaded packages
			display_info 'Adding '$NAME' signing key to keyring...'
			# Import Key
			gpg --keyserver $KEYSERVER --recv-keys $KEYID
			# Done
			display_success 'Done.'
		else
			display_info $NAME 'signing key already in keyring.'
		fi
		# Install
		display_info 'Installing '$NAME'...'
		\curl -sSL https://get.rvm.io | bash -s stable --ruby
		# \curl -sSL https://get.rvm.io | bash # Uncomment for development version
		# Done
		display_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		thirdparty
	else
		# Already installed
		display_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		thirdparty
	fi
}