#!/bin/bash

# Slack
function slack {
	# Variables
	NAME="Slack"
	PACKAGE=slack-desktop
	VERSION=2.6.3
	# Install
	display_header 'Begin '$NAME' installation'
	# Check if package is installed
	check_packages $PACKAGE
	EXITSTATUS=$?
	# If package is not installed
	if [ $EXITSTATUS = 1 ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		display_info 'Downloading '$NAME'...'
		# Download Debian file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				curl -O https://downloads.slack-edge.com/linux_releases/slack-desktop-${VERSION}-i386.deb
				;;
			x86_64)
				curl -O https://downloads.slack-edge.com/linux_releases/slack-desktop-${VERSION}-amd64.deb
				;;
			*)
				whiptail --title "Error." --msgbox "No remote packages available to download." 8 64
				;;
		esac
		# Install package(s)
		display_info 'Installing '$NAME'...'
		elevate_privilege "dpkg -i $PACKAGE*.deb"
		elevate_privilege "apt install -fy"
		# Cleanup and finish
		rm ${PACKAGE}-*.deb
		# Done
		display_success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		display_info $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}