#!/bin/bash

# Spotify
function spotify {
	# Variables
	NAME="Spotify"
	PACKAGE=spotify-client
	LIST=spotify.list
	KEYID='BBEBDCB318AD50EC6865090613B00F1FD2C19886'
	KEYSERVER='hkp://keyserver.ubuntu.com:80'
	REPO='deb http://repository.spotify.com stable non-free'
	# Install
	echo_message header 'Begin '$NAME' installation'
	# Check if package is installed
	check_packages $PACKAGE
	EXITSTATUS=$?
	# If package is not installed
	if [ $EXITSTATUS = 1 ]; then
		echo_message info $NAME 'is not installed.'
		echo 'Proceeding'
		# Check if key already exists in keyring
		KEYCHECK=$(apt-key --list-keys | grep -w ${KEYID})
		if [ "" == "$KEYCHECK" ]; then
			# Add the repository signing key to be able to verify downloaded packages
			echo_message info 'Adding '$NAME' signing key to keyring...'
			# Import Key
			elevate_privilege "apt-key adv --keyserver $KEYSERVER --recv-keys $KEYID"
			# Done
			echo_message success "Installation of '$PACKAGE' complete."
		else
			echo_message info $NAME 'signing key already in keyring.'
		fi
		# Check if repository already exists
		echo_message info 'Checking if '$NAME' repository is already added...'
		if [ ! -f /etc/apt/sources.list.d/${LIST} ]; then
			# Add the repository
			echo_message info 'Adding '$NAME' repository to software sources...'
			# Write repository to apt sources list file
			echo $REPO | elevate_privilege "tee /etc/apt/sources.list.d/${LIST}"
			# Update repository information
			echo_message info 'Updating repository information...'
			elevate_privilege "apt update -y"
			echo_message success "Installation of '$PACKAGE' complete."
		else
			echo_message info $NAME 'repository already in software sources.'
		fi
		# Install
		echo_message info 'Installing '$NAME'...'
		elevate_privilege "apt install -y $PACKAGE"
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		echo_message info $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}