#!/bin/bash

# Spotify
function spotify {
	# Variables
	NAME="Spotify"
	PACKAGE=spotify-client
	LIST=spotify.list
	KEYID='BBEBDCB318AD50EC6865090613B00F1FD2C19886'
	KEYSERVER='hkp://keyserver.ubuntu.com:80'
	REPO='deb http://repository.spotify.com stable non-free'
	# Install
	display_header 'Begin '$NAME' installation'
	# Check if already installed
	display_info 'Checking if '$NAME' already installed...'
	PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	if [ "" == "$PKGCHECK" ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		# Check if key already exists in keyring
		KEYCHECK=$(apt-key --list-keys | grep -w ${KEYID})
		if [ "" == "$KEYCHECK" ]; then
			# Add the repository signing key to be able to verify downloaded packages
			display_info 'Adding '$NAME' signing key to keyring...'
			display_warning 'Requires admin privileges'
			# Import Key
			$SUDOCMD apt-key adv --keyserver $KEYSERVER --recv-keys $KEYID
			# Done
			display_success 'Done.'
		else
			display_info $NAME 'signing key already in keyring.'
		fi
		# Check if repository already exists
		display_info 'Checking if '$NAME' repository is already added...'
		if [ ! -f /etc/apt/sources.list.d/${LIST} ]; then
			# Add the repository
			display_info 'Adding '$NAME' repository to software sources...'
			display_warning 'Requires admin privileges'
			# Write repository to apt sources list file
			echo $REPO | $SUDOCMD tee /etc/apt/sources.list.d/${LIST}
			# Update repository information
			display_info 'Updating repository information...'
			$SUDOCMD apt update -y
			display_success 'Done.'
		else
			display_info $NAME 'repository already in software sources.'
		fi
		# Install
		display_info 'Installing '$NAME'...'
		$SUDOCMD apt install -y $PACKAGE
		# Done
		display_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		thirdparty
	else
		# Already installed
		display_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		thirdparty
	fi
}