#!/bin/bash

# Steam
function steam {
	# Variables
	NAME="Steam"
	PACKAGE=steam
	# Install
	echo_message header 'Begin '$NAME' installation'
	# Check if package is installed
	check_packages $PACKAGE
	EXITSTATUS=$?
	# If package is not installed
	if [ $EXITSTATUS = 1 ]; then
		echo_message info $NAME 'is not installed.'
		echo 'Proceeding'
		echo_message info 'Downloading '$NAME'...'
		# Download Debian file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				curl -O http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
				;;
			x86_64)
				curl -O http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
				;;
			*)
				whiptail --title "Error." --msgbox "No remote packages available to download." 8 64
				;; 
		esac
		# Install package(s)
		echo_message info 'Installing '$NAME'...'
		elevate_privilege "dpkg -i $PACKAGE*.deb"
		elevate_privilege "apt install -fy"
		# Install dependencies
		echo_message info 'Installing '$NAME' dependencies...'
		elevate_privilege "apt install -y libgl1-mesa-glx libgl1-mesa-dev libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libc6:i386"
		# Cleanup and finish
		rm $PACKAGE*.deb
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		echo_message info $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}