#!/bin/bash

# Steam
function steam {
	# Variables
	NAME="Steam"
	PACKAGE=steam
	# Install
	display_header 'Begin '$NAME' installation'
	# Check if package is installed
	check_packages $PACKAGE
	exitstatus=$?
	# If package is not installed
	if [ $exitstatus = 1 ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		display_info 'Downloading '$NAME'...'
		# Download Debian file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				curl -O http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
				;;
			x86_64)
				curl -O http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
				;;
			*)
				whiptail --title "No remote packages available to download." --msgbox "Error." 8 64
				;; 
		esac
		# Install package(s)
		display_info 'Installing '$NAME'...'
		elevate_privilege "dpkg -i $PACKAGE*.deb"
		elevate_privilege "apt install -fy"
		# Install dependencies
		display_info 'Installing '$NAME' dependencies...'
		elevate_privilege "apt install -y libgl1-mesa-glx libgl1-mesa-dev libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libc6:i386"
		# Cleanup and finish
		rm $PACKAGE*.deb
		# Done
		display_success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		thirdparty
	else
		# Already installed
		display_info $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}