#!/bin/bash

# Steam
function steam {
	# Variables
	NAME="Steam"
	# Install
	display_header 'Begin '$NAME' installation'
	# Check if already installed
	display_info 'Checking if '$NAME' already installed...'
	PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
	if [ "" == "$PKGCHECK" ]; then
		display_info $NAME 'is not installed.'
		echo 'Proceeding'
		display_info 'Downloading '$NAME'...'
		# Download Debian file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				curl -O http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
				;;
			x86_64)
				curl -O http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
				;;
			*)
				whiptail --title "No remote packages available to download." --msgbox "Error." 8 78
				;; 
		esac
		# Install package(s)
		display_info 'Installing '$NAME'...'
		display_warning 'Requires admin privileges'
		$SUDOCMD dpkg -i steam*.deb
		$SUDOCMD apt install -fy
		# Install dependencies
		display_info 'Installing '$NAME' dependencies...'
		display_warning 'Requires admin privileges'
		$SUDOCMD apt install -y libgl1-mesa-glx libgl1-mesa-dev libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libc6:i386
		# Cleanup and finish
		rm steam*.deb
		# Done
		display_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		thirdparty
	else
		# Already installed
		display_success $NAME 'already installed.'
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		thirdparty
	fi
}